# Key strings
COMMAND_KEY = "COMMAND"
SUCCESFULLY_PROCESSED_COMMAND_KEY = "SUCCESSFULLY_PROCESSED_COMMAND"
# Command strings
CMD_GET_SYSTEM_INFO = "GET_SYSTEM_INFO"
CMD_GET_USER_LOGGED_IN = "GET_USER_LOGGED_IN"
