http://localhost:8080/api/user/fmoras01

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "name": "fmoras01",
  "password": "nacienel67"
}

###

http://localhost:8080/api/login/jwtprotected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZGNiZjIzZWE1YzM0OGZhZTk5ZDZiYjUiLCJuYW1lIjoicHJvZmVzb3IiLCJleHAiOjE1Nzk3NzI4MTU5NzUsImNyZWF0ZWRBdExvY2FsZSI6IjIwMTktMTEtMTMgMTM6MDg6MzAiLCJ1cGRhdGVkQXRMb2NhbGUiOiIyMDIwLTAxLTIzIDEwOjQ1OjI5IiwiZnVsbE5hbWUiOiJQcm9mZXNvciwgUHJvZmVzb3IgKHByb2Zlc29yKSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE1Nzk3NzI3Mjl9.20GWUmuxxh37qPIpiq31TiZVxa8PVvZIbOSaiOBcnXg

###

http://localhost:8080/api/ldap/user/fmoras01